### ISSUE TITLE
Small issues in El_Salvador scenarios

### ISSUE THREAD

**Issue by alejocaldeGEM** [gem/earthquake-scenarios#17]
## Requesting Changes
The local experts in El Salvador have requested a change in the name for the two events in the country. I would suggest to follow their suggestions (see below) to the make the events more familiar to users in El Salvador:

| Current Name | Suggested Name |
|---|---|
| 20010113_M7.6_SanMiguel | 20010113_M7.6_Subduccion |
| 20010213_M6.6_SanSalvador | 20010213_M6.6_SanVicente |

## Issues

1. In `El_Salvador/20010113_M7.6_SanMiguel/Recording_Stations` there seems to be additional station images that do not belong to this event. Two are for events in Haiti, and another one for an event in Kashmir. These should be removed.

2. job.ini files in the `OpenQuake_gmfs` do not work out of the box. The rupture files cannot be found because the path provided in the job.ini are of the following form:

>`rupture_model_file = ../Ground_Shaking/Rupture/earthquake_rupture_model_GCMT.xml`

However, the `Ground_Shaking` folder is not there. By removing that folder from the path the job.ini files work properly. I experienced this in the scenarios for El Salvador, but might be in the files for other countries as well

**Comment by CatalinaYepes** [comment]
Additional modifications needed:
- Review seismic station data and review stations marked as outliers by the USGS
- Review GMPE logic trees for San Vicente (Active shallow instead of subduction)
- Include maximum distance when conditioning the gmf to stations
- Modify site model to be finer at populated centres
- Fix and update job files
- Update runs

**Comment by CatalinaYepes** [comment]
Close with #30
